### ISSUE TITLE
近期有没有升级webpack5的打算？

### ISSUE THREAD

**Issue by dxhuii** [dxx/react-bilibili#13]
我自己尝试升级，遇到一个问题，无法解决

```js
Your app is running
(node:78354) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
webpack built 557c9f15e8f62ac12901 in 4803ms
No issues found.
======enter server======
visit url: /
[class ServerRenderer] serverEntry
TypeError: createStore is not a function
    at /Users/dingxiaohui/Documents/web/react-ssr/server/renderer.js:23:21
    at new Promise (<anonymous>)
    at ServerRenderer.renderToString (/Users/dingxiaohui/Documents/web/react-ssr/server/renderer.js:14:12)
    at render (/Users/dingxiaohui/Documents/web/react-ssr/server/index.js:36:12)
    at /Users/dingxiaohui/Documents/web/react-ssr/server/index.js:53:27
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
======enter server======
visit url: /favicon.ico
```

目前就这一个错误了，如果你有打算升级webpack5,到时候可以学习一下。

**Comment by dxx** [comment]
目前没有升级的打算哈。

这个看起来是 webpack 打包后的 js 代码在 vm 中获取 `createStore` 的问题，看看服务端入口 js 打包后长啥样，通过 vm 获取对应服务端入口文件 `export` 出来的函数。
